VideoChat/Controllers/GeoLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoChat.Managers;
using VideoChat.Models;
using ubs.GeoBazaAPI;

namespace VideoChat.Controllers
{
    public class GeoLocationController : Controller
    {
        private Data data = new Data(); 

        public ActionResult Index()
        {
            // получаем ip клиента (если не локальный хост)
            string IP = HttpContext.Request.UserHostAddress;

            if(IP=="::1")
            {
                IP = System.Configuration.ConfigurationManager.AppSettings["CurrentIP"];
            }

            // получаем географию
            string coordinates = "";
            GeoManager geomanager = new GeoManager();
            ViewBag.Location = geomanager.DefineLocation(IP, ref coordinates, Server.MapPath("~/GeoBD/geobaza.dat"));
            ViewBag.Coords = coordinates;

            return View();
        }

       
    }
}

VideoChat/Controllers/ModeratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoChat.Models;
using PagedList;
using VideoChat.Providers;


namespace VideoChat.Controllers
{
    [AuthorizeUser(Roles = "Admin, Moderator")]
    public class ModeratorController : Controller
    {
        private Data data = new Data();

        public ActionResult Index(int? page)
        {
            try
            {                
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                var data = new Data();
                var model = data.GetUsersStore().GetKeyWordList().ToList().ToPagedList(pageNumber, pageSize);
                
                return View(model);
            }

            catch (Exception exp)
            {
                return View("Error");
            }

        }


        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception exp)
            {
                return View("Error");
            }

        }


        [HttpPost]
        public ActionResult Create(KeyWord model)
        {
            try
            {
                model.ModeratorKey = Request.Cookies["key"].Value;
                model.Key = data.GetUsersStore().GetMaxIdForkey()+1;
                data.GetUsersStore().AddKeyWord(model);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }


        public ActionResult Edit(int id)
        {
            try
            {
                var model = data.GetUsersStore().GetKeyById(id);

                return View(model);
            }
            catch (Exception exp)
            {
                return View("Error");
            }
        }

        public ActionResult Details(int id)
        {
            try
            {
                var model = data.GetUsersStore().GetKeyById(id);

                return View(model);
            }
            catch (Exception exp)
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, KeyWord model)
        {
            try
            {
                model.Key = id;
                data.GetUsersStore().EditKeyWord(model);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }


        public ActionResult Delete(int id)
        {
            try
            {
                var model = data.GetUsersStore().GetKeyById(id);

                return View(model);
            }
            catch (Exception exp)
            {
                return View("Error");
            }
        }


        [HttpPost]
        public ActionResult Delete(int id, KeyWord model)
        {
            try
            {
                data.GetUsersStore().DeleteKeyWord(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

VideoChat/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title </title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Scripts.Render("~/Scripts/rainyday.js")
    @Scripts.Render("~/Scripts/rainydayApp.js")
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

</head>
<body onload="demoRunApp()">
    <img id="background" src="~/Content/img/I2tZMAg.jpg" />
    <div id="cholder">
        <canvas id="canvas"></canvas>
    </div>
    <div class="layout-container">
        <div class="container-fluid">
            <div id="header" class="row-fluid">
                <br />
            </div>
            <audio id="callSound" style="display: none;" src="/call.wav" controls preload="auto" autobuffer>
            </audio>
            <audio id="chatSound" style="display: none;" src="/ding.wav" controls preload="auto" autobuffer>
            </audio>
            <div id="" class="row-fluid">
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container-fluid">

                            <a class="brand" id="userName" href="#">Ваше имя</a>
                            <a class="brand" href="@Url.Action("Index", "Home")">приветствуем вас в <span>VideoChat</span> </a>
                            <a class="brand" id="logoutLink" href="@Url.Action("LogOut", "Home")">Выйти </a>
                            @if (ViewContext.HttpContext.Request.Cookies["role"] != null)
                            {

                                if (ViewContext.HttpContext.Request.Cookies["role"].Value == "Admin")
                                {
                                <a class="brand" id="moderatorPanelLink" href="@Url.Action("Index", "Moderator")">Панель модератора</a>
                                      
                                <a class="brand" id="geoLocationsLink" href="@Url.Action("Index", "GeoLocation")">География 
                                </a>
                                <a class="brand" id="moderatorPanelLink" href="@Url.Action("Index", "Admin")">Панель администратора</a>
                                }
                                if (ViewContext.HttpContext.Request.Cookies["role"].Value == "Moderator")
                                {
                                <a class="brand" id="moderatorPanelLink" href="@Url.Action("Index", "Moderator")">Панель модератора</a>
                                <a class="brand" id="geoLocationsLink" href="@Url.Action("Index", "GeoLocation")">География пользователей </a>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div id="" class="row-fluid">
                @RenderBody()
            </div>
            <div id="footer" class="row-fluid">
            </div>
        </div>
    </div>

    @Scripts.Render("~/Scripts/jquery-1.8.2.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/bootstrap.js")
    @Scripts.Render("~/Scripts/app.js")

    <script src="@Url.Content("~/Scripts/jquery.signalR-0.5.3.min.js")" type="text/javascript"></script>
    <script src="/signalr/hubs" type="text/javascript"></script>
    @RenderSection("scripts", required: false)


</body>
</html>